[SC-306] lambda docker runner
Sage-Bionetworks-IT/lambda-docker-runner pull request #2
Opened 2021-03-09 16:19 UTC by zaro0508

Setup a lambda to execute docker containers. Users can execute the docker
with a REST API request or they can configure it to run on a schedule. 

Lambdas have a hard storage limit of 512MB so we integrate this lambda
with an an elastic file system (EFS) which will auto scale to whatever
storage the user app needs.

Containers images referenced by this lambda must meet the following requirements
https://docs.aws.amazon.com/lambda/latest/dg/images-create.html#images-reqs

AWS provides container base images for the following environments::
https://docs.aws.amazon.com/lambda/latest/dg/runtimes-images.html

2021-03-12 02:03 UTC, zimingd requested changes

2021-03-12 17:22 UTC, zaro0508 commented on template.yaml
> +  EnableSchedule:
I guess so but will require more complexity in yaml code.  why do you ask?  do you think it will make it easier to understand?

2021-03-12 18:28 UTC, ahayden reviewed
GH comments are failing... I'll have to come back

2021-03-12 18:28 UTC, ahayden commented on samconfig.toml
>  s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4h9lffzdpzzw"
Is this a static name for resources the AWS SAM client uses, or is it yours?

2021-03-12 18:28 UTC, ahayden commented on samconfig.toml
> +parameter_overrides = "SecurityGroupIds=\"sg-0c625e6cfa9c17e33\" SubnetIDs=\"subnet-0aa9c73cbf165d4a0,subnet-07d44829944aea30f,subnet-05c3b8e6ce902c43f\" EFSpath=\"/mnt/efs\" AccessPointARN=\"arn:aws
This is just a test case, right?

2021-03-12 18:28 UTC, ahayden commented on template.yaml
> +          - SynapseUser
Flagging this line for Bruce's comments about Synapse PAT

2021-03-12 18:28 UTC, ahayden commented on template.yaml
> +          - ImageUri
There are multiarch containers now... I wonder if possible to specify arch by parameter or if just defaults to amd64? https://aws.amazon.com/blogs/containers/introducing-multi-architecture-container-images-for-amazon-ecr/

2021-03-12 19:04 UTC, zaro0508 commented on template.yaml
> +          - ImageUri
no, lambda only supports awslinx 2 distro. 
 https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

we would need to move to batch to be able to specify a specific AMI to use.

2021-03-12 19:04 UTC, zaro0508 commented on samconfig.toml
> +parameter_overrides = "SecurityGroupIds=\"sg-0c625e6cfa9c17e33\" SubnetIDs=\"subnet-0aa9c73cbf165d4a0,subnet-07d44829944aea30f,subnet-05c3b8e6ce902c43f\" EFSpath=\"/mnt/efs\" AccessPointARN=\"arn:aws
yes, this is a SAM deployment file.  i committed it to let you see how params are passed in for deployment.  we are not going to use this file, instead we are going to pass in these params when the lambda get provisioned in the SC.  Please ignore this file.

2021-03-12 19:39 UTC, ahayden commented on template.yaml
> +  EnableSchedule:
I kind of like having the `EnableSchedule` boolean and then a default schedule if enabled... IMO its simpler for end users to have an on/off switch rather than having to figure out cron syntax

2021-03-12 21:28 UTC, ahayden approved these changes
Added a few new questions

2021-03-12 21:28 UTC, ahayden commented on template.yaml
> +          - ImageUri
yeah, those are all x86_64 envs

2021-03-12 21:28 UTC, ahayden commented on template.yaml
> +            Resource: "*"
Should this specify the access point arn rather than `*`?

2021-03-12 22:14 UTC, zaro0508 commented on template.yaml
> +            Resource: "*"
hmm, i basically took this from AWS example here: https://github.com/aws-samples/aws-lambda-efs-samples/blob/master/2-lambda-template/template.yaml#L52

I'm guessing that it cannot be restricted to just the EFS resource.

2021-03-13 02:39 UTC, brucehoff requested changes

2021-03-19 04:46 UTC, zaro0508 commented
a lambda is not needed for this.  we can do this with a straight up cloudformation template and that's done in https://github.com/Sage-Bionetworks/service-catalog-library/pull/242

2021-03-19 04:46 UTC, closed without merging